#!/bin/bash
echo "🔍 Verifying StateChart Editor installation..."
echo ""
echo "✅ Dependencies:"
npm list @xyflow/react react react-dom 2>/dev/null | grep -E "@xyflow|react" || echo "❌ Missing dependencies"
echo ""
echo "✅ Compiled files:"
[ -f "out/statechart/stateChartEditor.js" ] && echo "  ✓ Extension compiled" || echo "  ✗ Extension NOT compiled"
[ -f "media/stateChartWebview.js" ] && echo "  ✓ Webview bundle exists" || echo "  ✗ Webview bundle MISSING"
echo ""
echo "✅ Example files:"
ls -1 ../../examples/statecharts/*.statechart.json 2>/dev/null || echo "  ✗ No example files found"
echo ""
echo "🚀 To test the editor:"
echo "  1. Open VS Code at the trust-platform repository root"
echo "  2. Press F5 to run the extension in development mode"
echo "  3. In the development window, open: examples/statecharts/traffic-light.statechart.json"
echo "  4. The visual editor should open automatically"
echo ""
