pub(super) const PROTOCOL_IDS: [&str; 15] = [
    "modbus_tcp",
    "mqtt",
    "ethercat",
    "gpio",
    "simulated",
    "loopback",
    "opcua",
    "opcua_client",
    "openot",
    "discovery",
    "mesh",
    "realtime_t0",
    "runtime_cloud",
    "ads_server",
    "ads",
];

pub(super) const IO_PROTOCOL_IDS: [&str; 6] = [
    "modbus_tcp",
    "mqtt",
    "ethercat",
    "gpio",
    "simulated",
    "loopback",
];

pub(super) const DIRECT_RUNTIME_PROTOCOL_IDS: [&str; 7] = [
    "opcua",
    "openot",
    "discovery",
    "mesh",
    "realtime_t0",
    "runtime_cloud",
    "ads_server",
];

pub(super) const ACTION_VOCABULARY: [&str; 10] = [
    "add",
    "edit",
    "upsert",
    "remove",
    "disable",
    "discover",
    "browse_symbols",
    "test",
    "doctor",
    "route_script",
];

pub(super) const FIELD_TYPE_VOCABULARY: [&str; 9] = [
    "string",
    "secret",
    "boolean",
    "number",
    "enum",
    "endpoint",
    "path",
    "json_array",
    "json_object",
];

pub(super) fn protocol_field_ids(protocol_id: &str) -> &'static [&'static str] {
    match protocol_id {
        "modbus_tcp" => &[
            "address",
            "unit_id",
            "input_start",
            "output_start",
            "timeout_ms",
            "on_error",
        ],
        "mqtt" => &[
            "broker",
            "client_id",
            "topic_in",
            "topic_out",
            "username",
            "password",
            "tls",
            "allow_insecure_remote",
            "reconnect_ms",
            "keep_alive_s",
            "on_error",
            "tls_ca_path",
            "tls_client_cert_path",
            "tls_client_key_path",
            "tls_alpn",
        ],
        "ethercat" => &[
            "adapter",
            "timeout_ms",
            "cycle_warn_ms",
            "on_error",
            "modules",
            "mock_inputs",
            "selected_channels",
        ],
        "gpio" => &["backend", "chip", "sysfs_base", "inputs", "outputs"],
        "simulated" => &["input_count", "output_count", "scan_period_ms", "mode"],
        "loopback" => &["input_count", "output_count", "scan_period_ms", "mode"],
        "opcua" => &[
            "enabled",
            "listen",
            "endpoint_path",
            "namespace_uri",
            "publish_interval_ms",
            "max_nodes",
            "expose",
            "security_policy",
            "security_mode",
            "allow_anonymous",
            "username",
            "password",
        ],
        "opcua_client" => &["enabled", "config_path", "poll_interval_ms", "connections"],
        "openot" => &[
            "enabled",
            "path",
            "capacity",
            "fence_mode",
            "allow_unfenced_for_proof",
            "source",
            "producer_instances",
        ],
        "discovery" => &[
            "enabled",
            "service_name",
            "advertise",
            "interfaces",
            "host_group",
        ],
        "mesh" => &[
            "enabled",
            "role",
            "listen",
            "connect",
            "tls",
            "auth_token",
            "publish",
            "subscribe",
            "zenohd_version",
            "plugin_versions",
        ],
        "realtime_t0" => &[
            "enabled",
            "require_preempt_rt_kernel",
            "lock_memory",
            "scheduler",
            "priority",
            "cpu_affinity",
            "strict",
        ],
        "runtime_cloud" => &["profile", "wan_allow_write", "link_transports"],
        "ads_server" => &[
            "enabled",
            "listen",
            "ams_net_id",
            "ads_port",
            "insecure_transport",
            "writes_enabled",
            "expose",
            "writable",
            "allow_unpinned_clients",
            "clients",
            "max_symbols",
            "max_clients",
            "max_subscriptions_per_client",
            "max_total_subscriptions",
            "max_frame_bytes",
            "max_sumup_items",
            "max_write_bytes",
        ],
        "ads" => &[
            "enabled",
            "config_path",
            "worker_tick_interval_ms",
            "connections",
        ],
        _ => panic!("no field authority for protocol {protocol_id}"),
    }
}
