"""Shared vocabulary for the verification metadata validator."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
VERIFICATION = ROOT / "verification"

AREAS = {
    "compiler_iec",
    "bytecode_vm",
    "runtime_safety",
    "protocols",
    "control_security",
    "editor_safety",
    "plcopen_devtools",
    "hmi_ui",
    "release",
    "supply_chain_platform",
    "verification",
}
SUITE_AREA = "suite"

STATUSES = {
    "planned",
    "mapped",
    "gap_open",
    "spec_gap",
    "test_written",
    "implemented",
    "validated",
    "blocked",
    "deferred",
    "rejected",
    "unproven",
}
COVERAGE_STATES = {
    "covered",
    "covered_by_fuzz",
    "not_applicable",
    "blocked",
    "spec_gap",
    "gap_open",
    "deferred",
}
SOURCE_AUTHORITIES = {
    "normative_external",
    "normative_product",
    "reviewed_decision",
    "reviewed_deviation",
    "public_claim",
}
SOURCE_STATUSES = {
    "active",
    "draft",
    "stale",
    "superseded",
    "missing",
    "conflicting",
}
RISKS = {
    "safety_critical",
    "wrong_result",
    "silent_corruption",
    "false_status",
    "data_loss",
    "security",
    "compatibility",
    "performance",
    "usability",
    "maintenance",
    "supply_chain",
    "platform",
}
HIGH_RISKS = {
    "safety_critical",
    "wrong_result",
    "silent_corruption",
    "false_status",
}
PROOF_LEVELS = {"S0", "S1", "D1", "T1", "D2", "I1", "G1", "G2", "R1"}
PROOF_LEVELS_VALIDATED = {"G1", "G2", "R1"}
CONTRACT_KINDS = {
    "decision_table",
    "state_machine",
    "protocol_trace",
    "fault_scenario",
    "ui_journey",
    "security_policy",
    "perf_budget",
    "release_matrix",
}
SPEC_STATUSES = {
    "specified",
    "ambiguous",
    "missing",
    "conflicting",
    "external_blocked",
}
ORACLE_KINDS = {
    "iec_standard",
    "protocol_standard",
    "trust_contract",
    "design_contract",
    "public_doc",
    "external_reference",
    "hardware_observation",
    "reviewed_decision",
    "reviewed_deviation",
    "release_contract",
}
RESOLUTION_STATUSES = {
    "open",
    "decision_recorded",
    "spec_updated",
    "test_mapped",
    "closed",
    "rejected",
}
GAP_CLASSES = {
    "missing_behavior",
    "ambiguous_behavior",
    "conflicting_sources",
    "missing_boundary",
    "missing_error_model",
    "missing_lifecycle",
    "missing_persistence",
    "missing_security",
    "missing_hardware_contract",
    "missing_ui_contract",
    "missing_user_workflow",
    "external_source_unavailable",
    "public_claim_unproven",
}
BLOCKS_VALUES = {"test_mapping", "release_claim", "none_yet"}
OUTCOMES = {
    "accept_value",
    "reject",
    "trap",
    "fault_visible",
    "not_safe_reported",
    "status_degraded",
}
PARTITION_KEYS = {"min", "max", "below", "above", "equals", "wrong_type", "malformed"}
DELTA_KEYS = {
    "target",
    "siblings",
    "retain",
    "process_image",
    "diagnostics",
    "status",
}
DELTA_VALUES = {
    "target": {"set_to_input", "set_to_expected", "unchanged", "not_applicable"},
    "siblings": {"unchanged", "expected_delta", "not_applicable"},
    "retain": {"unchanged", "expected_delta", "not_applicable"},
    "process_image": {"unchanged", "expected_delta", "not_applicable"},
    "diagnostics": {"none", "stable_error", "expected_diagnostic", "not_applicable"},
    "status": {"unchanged", "fault_visible", "status_degraded", "not_safe_reported", "not_applicable"},
}
CASE_FAMILIES = {
    "happy_path",
    "boundary_low",
    "boundary_high",
    "below_min",
    "above_max",
    "wrong_type_or_shape",
    "missing_required",
    "extra_or_unknown",
    "duplicate_or_collision",
    "ordering_or_lifecycle",
    "encoding_or_unicode",
    "resource_limit",
    "auth_or_permission",
    "persistence_or_recovery",
    "concurrency_or_cancellation",
    "time_or_clock_fault",
    "hardware_or_network_fault",
    "supply_chain_or_artifact_fault",
    "platform_or_filesystem_variation",
}
INTENTS = {"bugfix", "feature", "refactor", "docs", "test-refactor"}
TEST_CLASSES = {
    "debug_reproduction_probe",
    "failing_regression",
    "protective_red",
    "behavior_lock",
    "unit",
    "integration",
    "runtime_vertical",
    "iec_conformance",
    "negative_malformed_input",
    "fuzz",
    "property",
    "mutation",
    "miri_sanitizer_loom",
    "protocol_loopback",
    "hardware_lab",
    "soak_stability",
    "performance",
    "lsp_protocol",
    "vscode_extension",
    "browser_webview_visual",
    "ui_journey_acceptance",
    "rbac_security",
    "supply_chain_security",
    "platform_package",
    "release_docs",
    "architecture_diagram",
    "metadata_validation",
}
EVIDENCE_KINDS = {"committed_file", "ci_artifact", "release_object", "lab_report"}
PROOF_KINDS = {"red", "green", "lock_baseline", "lock_compare", "protective_red", "none"}
SCHEMA_FILES = {
    "bytecode-validator-mutation-report.schema.json",
    "invariant.schema.json",
    "suite.schema.json",
    "catalog.schema.json",
    "ignored-test.schema.json",
    "risk-register.schema.json",
    "evidence.schema.json",
    "spec-source.schema.json",
    "spec-gap.schema.json",
    "spec-matrix.schema.json",
    "matrix.schema.json",
    "case-file.schema.json",
    "case-artifact.schema.json",
}
PROVE_PRODUCER_RE = re.compile(r"^prove\.py v[0-9]+(?:\.[0-9]+)*$")
COMMIT_RE = re.compile(r"^(?:[0-9a-f]{7,40}|dirty:[0-9a-f]{7,40})$")

SCHEMA_REQUIRED_FIELDS = {
    "bytecode-validator-mutation-report.schema.json": [
        "schema_version",
        "id",
        "status",
        "shard_id",
        "test_id",
        "runner",
        "tool",
        "tool_version",
        "source_commit",
        "platform",
        "started_at",
        "finished_at",
        "case_file",
        "case_file_digest",
        "case_semantics",
        "blocked_case_ids_executed",
        "baseline_commands",
        "mutations",
        "summary",
        "survivors",
        "out_of_scope_case_ids",
        "out_of_scope_reason",
    ],
    "case-artifact.schema.json": [
        "schema_version",
        "test_id",
        "case_file",
        "case_file_digest",
        "helper_version",
        "cases",
    ],
    "case-file.schema.json": [
        "schema_version",
        "id",
        "title",
        "area",
        "owner",
        "status",
        "invariant",
        "generator",
        "generator_digest",
        "source_digest",
        "last_reviewed",
        "case",
    ],
    "catalog.schema.json": [
        "schema_version",
        "id",
        "test_class",
        "area",
        "path",
        "command",
        "owner",
        "status",
        "invariants",
        "expected_result",
        "suite_tiers",
        "requires_hardware",
        "requires_network",
        "duration_class",
    ],
    "evidence.schema.json": [
        "schema_version",
        "id",
        "title",
        "area",
        "owner",
        "status",
        "kind",
        "commit",
        "platform",
        "date",
        "producer",
        "generated_report_version",
        "linked_invariants",
        "linked_tests",
        "last_reviewed",
    ],
    "ignored-test.schema.json": [
        "schema_version",
        "id",
        "test_id",
        "owner",
        "area",
        "status",
        "ignore_class",
        "reason",
        "unblock_condition",
        "last_reviewed",
    ],
    "invariant.schema.json": [
        "schema_version",
        "id",
        "title",
        "area",
        "risk",
        "status",
        "owner",
        "claim",
        "contract_kind",
        "proof_level",
        "tests",
        "gates",
        "missing",
        "spec",
        "oracle",
        "coverage",
    ],
    "matrix.schema.json": [
        "schema_version",
        "id",
        "title",
        "status",
        "owner",
        "last_reviewed",
        "areas",
        "intent_requirements",
    ],
    "risk-register.schema.json": [
        "schema_version",
        "id",
        "title",
        "area",
        "risk",
        "owner",
        "status",
        "last_reviewed",
        "description",
        "mitigation",
        "related_invariants",
    ],
    "spec-gap.schema.json": [
        "schema_version",
        "id",
        "title",
        "area",
        "risk",
        "owner",
        "status",
        "gap_class",
        "blocking_question",
        "affected_invariants",
        "candidate_spec_sources",
        "resolution_status",
        "last_reviewed",
    ],
    "spec-matrix.schema.json": [
        "schema_version",
        "id",
        "area",
        "tag",
        "title",
        "owner",
        "status",
        "expected_authority",
        "blocks",
        "last_reviewed",
    ],
    "spec-source.schema.json": [
        "schema_version",
        "id",
        "title",
        "area",
        "owner",
        "status",
        "authority",
        "source_status",
        "visibility",
        "covers",
        "known_limitations",
    ],
    "suite.schema.json": [
        "schema_version",
        "id",
        "title",
        "area",
        "owner",
        "status",
        "last_reviewed",
        "purpose",
        "duration_class",
        "environment",
        "commands",
        "evidence_destination",
    ],
}
