[package]
name = "trust-runtime-core"
description = "Portable execution core scaffold for the truST runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
smol_str.workspace = true
thiserror.workspace = true
