use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use trust_ads_core::{
    AdsDataTypeDescriptor, IecDataType, SymbolSnapshot, SYMBOL_SNAPSHOT_SCHEMA_VERSION,
};

use super::contracts::{AdsClientConfig, AdsConnectionConfig};
use super::descriptors::validate_point_against_symbols;
use super::transport::AdsPointAddress;

const QUALITY_TYPE_NAME: &str = "ADS_QUALITY";
const QUALITY_INITIAL_STATE: &str = "Stale";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AdsGeneratedInterface {
    pub source: String,
    pub point_count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AdsInterfaceError {
    MissingSnapshot {
        route_name: String,
    },
    DuplicateSnapshot {
        route_name: String,
    },
    UnsupportedSnapshotSchema {
        route_name: String,
        expected: u16,
        actual: u16,
    },
    InvalidIdentifier {
        point_name: String,
    },
    DuplicateGeneratedName {
        name: String,
    },
    QualityNameCollision {
        point_name: String,
        quality_name: String,
    },
    PointDescriptor {
        point_name: String,
        detail: String,
    },
    InvalidType {
        point_name: String,
        detail: String,
    },
}

impl fmt::Display for AdsInterfaceError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingSnapshot { route_name } => {
                write!(f, "ADS snapshot for route '{route_name}' is missing")
            }
            Self::DuplicateSnapshot { route_name } => {
                write!(
                    f,
                    "ADS snapshot for route '{route_name}' was provided more than once"
                )
            }
            Self::UnsupportedSnapshotSchema {
                route_name,
                expected,
                actual,
            } => write!(
                f,
                "ADS snapshot for route '{route_name}' uses schema {actual}; expected {expected}"
            ),
            Self::InvalidIdentifier { point_name } => write!(
                f,
                "ADS point '{point_name}' is not a valid generated ST identifier"
            ),
            Self::DuplicateGeneratedName { name } => {
                write!(f, "generated ADS interface name '{name}' is duplicated")
            }
            Self::QualityNameCollision {
                point_name,
                quality_name,
            } => write!(
                f,
                "ADS point '{point_name}' collides with generated quality variable '{quality_name}'"
            ),
            Self::PointDescriptor { point_name, detail } => {
                write!(
                    f,
                    "ADS point '{point_name}' failed snapshot validation: {detail}"
                )
            }
            Self::InvalidType { point_name, detail } => {
                write!(
                    f,
                    "ADS point '{point_name}' cannot be emitted as ST: {detail}"
                )
            }
        }
    }
}

impl std::error::Error for AdsInterfaceError {}

pub fn generate_ads_interface(
    config: &AdsClientConfig,
    snapshots: &[SymbolSnapshot],
) -> Result<AdsGeneratedInterface, AdsInterfaceError> {
    let snapshots = snapshot_index(snapshots)?;
    validate_generated_names(config)?;
    validate_config_against_snapshots(config, &snapshots)?;

    let mut source = String::new();
    source.push_str("(* Generated by trust-runtime ads import-symbols. Do not edit by hand. *)\n");
    source.push_str("TYPE\n");
    source.push_str(&format!(
        "    {QUALITY_TYPE_NAME} : (Stale := 0, Good := 1, Error := 2);\n"
    ));
    source.push_str("END_TYPE\n");
    source.push('\n');
    source.push_str("VAR_GLOBAL\n");
    let mut point_count = 0usize;
    for connection in &config.connections {
        source.push_str(&format!(
            "    (* ADS connection: {} *)\n",
            sanitize_st_comment(connection.route.name.as_str())
        ));
        for point in &connection.points {
            let ty = st_type_name(&point.data_type).map_err(|detail| {
                AdsInterfaceError::InvalidType {
                    point_name: point.point_name.clone(),
                    detail,
                }
            })?;
            source.push_str(&format!(
                "    (* {} *)\n",
                sanitize_st_comment(address_comment(&point.address).as_str())
            ));
            source.push_str(&format!("    {} : {};\n", point.point_name, ty));
            source.push_str(&format!(
                "    {} : {} := {};\n",
                quality_name(point.point_name.as_str()),
                QUALITY_TYPE_NAME,
                QUALITY_INITIAL_STATE
            ));
            point_count += 1;
        }
    }
    source.push_str("END_VAR\n");
    Ok(AdsGeneratedInterface {
        source,
        point_count,
    })
}

pub(super) fn validate_config_against_snapshots(
    config: &AdsClientConfig,
    snapshots: &BTreeMap<&str, &SymbolSnapshot>,
) -> Result<(), AdsInterfaceError> {
    for connection in &config.connections {
        validate_connection_against_snapshot(connection, snapshots)?;
    }
    Ok(())
}

pub(super) fn snapshot_index(
    snapshots: &[SymbolSnapshot],
) -> Result<BTreeMap<&str, &SymbolSnapshot>, AdsInterfaceError> {
    let mut index = BTreeMap::new();
    for snapshot in snapshots {
        if snapshot.schema_version != SYMBOL_SNAPSHOT_SCHEMA_VERSION {
            return Err(AdsInterfaceError::UnsupportedSnapshotSchema {
                route_name: snapshot.route_name.clone(),
                expected: SYMBOL_SNAPSHOT_SCHEMA_VERSION,
                actual: snapshot.schema_version,
            });
        }
        if index
            .insert(snapshot.route_name.as_str(), snapshot)
            .is_some()
        {
            return Err(AdsInterfaceError::DuplicateSnapshot {
                route_name: snapshot.route_name.clone(),
            });
        }
    }
    Ok(index)
}

fn validate_connection_against_snapshot(
    connection: &AdsConnectionConfig,
    snapshots: &BTreeMap<&str, &SymbolSnapshot>,
) -> Result<(), AdsInterfaceError> {
    if connection.points.is_empty() {
        return Ok(());
    }
    let snapshot = snapshots
        .get(connection.route.name.as_str())
        .ok_or_else(|| AdsInterfaceError::MissingSnapshot {
            route_name: connection.route.name.clone(),
        })?;
    for point in &connection.points {
        validate_point_against_symbols(point, &snapshot.symbols).map_err(|err| {
            AdsInterfaceError::PointDescriptor {
                point_name: point.point_name.clone(),
                detail: err.to_string(),
            }
        })?;
    }
    Ok(())
}

fn validate_generated_names(config: &AdsClientConfig) -> Result<(), AdsInterfaceError> {
    let mut names = BTreeSet::new();
    let point_names = config
        .connections
        .iter()
        .flat_map(|connection| {
            connection
                .points
                .iter()
                .map(|point| point.point_name.as_str())
        })
        .collect::<BTreeSet<_>>();
    for point in config
        .connections
        .iter()
        .flat_map(|connection| connection.points.iter())
    {
        if !is_st_identifier(point.point_name.as_str()) {
            return Err(AdsInterfaceError::InvalidIdentifier {
                point_name: point.point_name.clone(),
            });
        }
        if !names.insert(point.point_name.clone()) {
            return Err(AdsInterfaceError::DuplicateGeneratedName {
                name: point.point_name.clone(),
            });
        }
        let quality = quality_name(point.point_name.as_str());
        if point_names.contains(quality.as_str()) {
            return Err(AdsInterfaceError::QualityNameCollision {
                point_name: point.point_name.clone(),
                quality_name: quality,
            });
        }
        if !names.insert(quality.clone()) {
            return Err(AdsInterfaceError::DuplicateGeneratedName { name: quality });
        }
    }
    Ok(())
}

fn st_type_name(descriptor: &AdsDataTypeDescriptor) -> Result<String, String> {
    let scalar = st_scalar_type_name(descriptor)?;
    if descriptor.dimensions.is_empty() {
        return Ok(scalar);
    }
    let bounds = descriptor
        .dimensions
        .iter()
        .map(|dimension| {
            if dimension.upper < dimension.lower {
                return Err(format!(
                    "array dimension upper {} is below lower {}",
                    dimension.upper, dimension.lower
                ));
            }
            Ok(format!("{}..{}", dimension.lower, dimension.upper))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");
    Ok(format!("ARRAY[{bounds}] OF {scalar}"))
}

fn st_scalar_type_name(descriptor: &AdsDataTypeDescriptor) -> Result<String, String> {
    let ty = match descriptor.iec_type {
        IecDataType::Bool => "BOOL".to_string(),
        IecDataType::Sint => "SINT".to_string(),
        IecDataType::Int => "INT".to_string(),
        IecDataType::Dint => "DINT".to_string(),
        IecDataType::Lint => "LINT".to_string(),
        IecDataType::Usint => "USINT".to_string(),
        IecDataType::Uint => "UINT".to_string(),
        IecDataType::Udint => "UDINT".to_string(),
        IecDataType::Ulint => "ULINT".to_string(),
        IecDataType::Real => "REAL".to_string(),
        IecDataType::Lreal => "LREAL".to_string(),
        IecDataType::Byte => "BYTE".to_string(),
        IecDataType::Word => "WORD".to_string(),
        IecDataType::Dword => "DWORD".to_string(),
        IecDataType::Lword => "LWORD".to_string(),
        IecDataType::String => {
            let len = descriptor
                .string_len
                .ok_or_else(|| "STRING requires a declared length".to_string())?;
            format!("STRING[{len}]")
        }
    };
    Ok(ty)
}

fn is_st_identifier(name: &str) -> bool {
    if is_reserved_st_identifier(name) {
        return false;
    }
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn is_reserved_st_identifier(name: &str) -> bool {
    const RESERVED: &[&str] = &[
        "ACTION",
        "ADS_QUALITY",
        "ARRAY",
        "AT",
        "BOOL",
        "BY",
        "BYTE",
        "CASE",
        "CLASS",
        "CONFIGURATION",
        "CONSTANT",
        "DATE",
        "DATE_AND_TIME",
        "DINT",
        "DO",
        "DT",
        "DWORD",
        "ELSE",
        "ELSIF",
        "END_ACTION",
        "END_CASE",
        "END_CLASS",
        "END_CONFIGURATION",
        "END_FOR",
        "END_FUNCTION",
        "END_FUNCTION_BLOCK",
        "END_IF",
        "END_INTERFACE",
        "END_METHOD",
        "END_NAMESPACE",
        "END_PROGRAM",
        "END_REPEAT",
        "END_RESOURCE",
        "END_STRUCT",
        "END_TYPE",
        "END_UNION",
        "END_VAR",
        "END_WHILE",
        "ERROR",
        "EXIT",
        "EXTENDS",
        "FALSE",
        "FOR",
        "FUNCTION",
        "FUNCTION_BLOCK",
        "GOOD",
        "IF",
        "IMPLEMENTS",
        "INT",
        "INTERFACE",
        "LDATE",
        "LDATE_AND_TIME",
        "LDT",
        "LINT",
        "LREAL",
        "LTIME",
        "LTIME_OF_DAY",
        "LTOD",
        "LWORD",
        "METHOD",
        "NAMESPACE",
        "OF",
        "ON",
        "POINTER",
        "PROGRAM",
        "REAL",
        "REF_TO",
        "REPEAT",
        "RESOURCE",
        "RETURN",
        "SINT",
        "STALE",
        "STRING",
        "STRUCT",
        "TASK",
        "THEN",
        "TIME",
        "TIME_OF_DAY",
        "TO",
        "TOD",
        "TRUE",
        "TYPE",
        "UDINT",
        "UINT",
        "ULINT",
        "UNION",
        "UNTIL",
        "USING",
        "USINT",
        "VAR",
        "VAR_ACCESS",
        "VAR_CONFIG",
        "VAR_EXTERNAL",
        "VAR_GLOBAL",
        "VAR_IN_OUT",
        "VAR_INPUT",
        "VAR_OUTPUT",
        "VAR_TEMP",
        "WHILE",
        "WORD",
        "WSTRING",
    ];

    let upper = name.to_ascii_uppercase();
    RESERVED.binary_search(&upper.as_str()).is_ok()
}

fn quality_name(point_name: &str) -> String {
    format!("{point_name}_quality")
}

fn address_comment(address: &AdsPointAddress) -> String {
    match address {
        AdsPointAddress::Symbol(name) => format!("symbol {name}"),
        AdsPointAddress::Index {
            index_group,
            index_offset,
            size,
        } => format!("index group=0x{index_group:08X} offset=0x{index_offset:08X} size={size}"),
    }
}

fn sanitize_st_comment(text: &str) -> String {
    text.replace("*)", "* )")
}
