"use strict";

function readAdsDiscoverySnapshot(evaluate) {
  return evaluate(
    ".react-flow",
    `var pane=d.querySelector('aside[aria-label="Discover devices"]');var discover=pane?.querySelector('[data-role="ads-discover"]');var toggle=pane?.querySelector('[data-role="ads-advanced-toggle"]');var custom=pane?.querySelector('[data-role="ads-custom-ports"]');var cards=[...d.querySelectorAll('[data-role="ads-computer"]')].map(function(card){var text=(card.textContent||'').replace(/\\s+/g,' ').trim();var netId=/AMS Net ID:\\s*([0-9.]+)/i.exec(text)?.[1]||'';var host=/Host:\\s*([^ ]+)/i.exec(text)?.[1]||'';var services=[...card.querySelectorAll('[data-ads-port]')].map(function(row){var radio=row.querySelector('input[type="radio"]');var rowText=(row.textContent||'').replace(/\\s+/g,' ').trim();var count=/([0-9]+)\\s+variables?/i.exec(rowText);return {port:Number(row.getAttribute('data-ads-port')),status:row.getAttribute('data-status')||'',visibility:row.getAttribute('data-result-visibility')||'',symbol_count:count?Number(count[1]):null,text:rowText,selected:Boolean(radio?.checked),selectable:Boolean(radio&&!radio.disabled)};});var browse=card.querySelector('[data-role="ads-browse-variables"]');return {text:text,ams_net_id:netId,host:host,local:/On the discovery computer/i.test(text),identity:card.getAttribute('data-identity')||'',state:card.getAttribute('data-state')||'',services:services,browse_disabled:Boolean(browse?.disabled),results_stale:Boolean(card.querySelector('[data-role="ads-results-stale"]')),recheck_visible:Boolean(card.querySelector('[data-role="ads-recheck-services"]')),probe_running:Boolean(card.querySelector('[data-role="ads-probe-progress"]'))};});var body=(pane?.textContent||'').replace(/\\s+/g,' ').trim();return {pane_open:Boolean(pane),discover_button_count:pane?[...pane.querySelectorAll('[data-role="ads-discover"]')].length:0,discover_text:(discover?.textContent||'').replace(/\\s+/g,' ').trim(),discover_state:discover?.getAttribute('data-state')||'',discover_disabled:Boolean(discover?.disabled),advanced_expanded:toggle?.getAttribute('aria-expanded')==='true',advanced_fields:pane?[...pane.querySelectorAll('[data-role="ads-host"],[data-role="ads-ams-net-id"],[data-role="ads-custom-ports"]')].length:0,custom_ports_value:custom?.value||'',custom_ports_invalid:custom?.getAttribute('aria-invalid')==='true',automatic_scope_copy:/this computer and the local network/i.test(body),legacy_twincat_choices:/Where is TwinCAT|Recommended TwinCAT|TwinCAT \\(ADS\\)/i.test(body),cards:cards,body_text:body};`
  );
}

module.exports = { readAdsDiscoverySnapshot };
