use std::collections::BTreeMap;

use trust_ads_core::{SymbolDescriptor, SymbolFlag};

use crate::system_symbols;
use crate::{
    AdsErrorCode, AdsServerAuditEvent, AdsServerAuditKind, AdsServerError, AmsNetIdBytes,
    AuditSink, ClientId, ClientPolicy, Clock, CommandId, RuntimeWritePort, SymbolSource, ValueIo,
};

/// ADS symbol handle-by-name index group.
pub const ADSIGRP_SYM_HNDBYNAME: u32 = 0xF003;
/// ADS symbol value-by-name index group.
pub const ADSIGRP_SYM_VALBYNAME: u32 = 0xF004;
/// ADS symbol value-by-handle index group.
pub const ADSIGRP_SYM_VALBYHND: u32 = 0xF005;
/// ADS release-symbol-handle index group.
pub const ADSIGRP_SYM_RELEASEHND: u32 = 0xF006;
/// ADS symbol info-by-name index group.
pub const ADSIGRP_SYM_INFOBYNAME: u32 = 0xF007;
/// ADS symbol-version index group.
pub const ADSIGRP_SYM_VERSION: u32 = 0xF008;
/// ADS extended symbol info-by-name index group.
pub const ADSIGRP_SYM_INFOBYNAMEEX: u32 = 0xF009;
/// ADS symbol-upload table index group.
pub const ADSIGRP_SYM_UPLOAD: u32 = 0xF00B;
/// ADS symbol-upload-info index group.
pub const ADSIGRP_SYM_UPLOADINFO: u32 = 0xF00C;
/// ADS datatype-upload table index group.
pub const ADSIGRP_SYM_DT_UPLOAD: u32 = 0xF00E;
/// ADS symbol-upload-info v2 index group.
pub const ADSIGRP_SYM_UPLOADINFO2: u32 = 0xF00F;
/// ADS sum-up read index group.
pub const ADSIGRP_SUMUP_READ: u32 = 0xF080;
/// ADS sum-up write index group.
pub const ADSIGRP_SUMUP_WRITE: u32 = 0xF081;
/// ADS sum-up read/write index group.
pub const ADSIGRP_SUMUP_READWRITE: u32 = 0xF082;
/// ADS extended sum-up read index group.
pub const ADSIGRP_SUMUP_READ_EX: u32 = 0xF083;

/// ADS notification mode: cyclic samples generated by the server.
pub const ADSTRANS_SERVERCYCLE: u32 = 3;
/// ADS notification mode: samples generated by the server when value bytes change.
pub const ADSTRANS_SERVERONCHA: u32 = 4;

const ADSSTATE_RUN: u16 = 5;
const DEFAULT_MAX_HANDLES_PER_CLIENT: usize = 4096;

/// Device info returned by ADS `ReadDeviceInfo`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeviceInfo {
    /// Major version byte.
    pub major_version: u8,
    /// Minor version byte.
    pub minor_version: u8,
    /// Build number.
    pub build: u16,
    /// Device name, truncated/padded to 16 bytes on the wire.
    pub name: String,
}

impl Default for DeviceInfo {
    fn default() -> Self {
        Self {
            major_version: 1,
            minor_version: 0,
            build: 0,
            name: "truST".to_string(),
        }
    }
}

/// ADS device state returned by ADS `ReadState`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AdsDeviceState {
    /// ADS state value.
    pub ads_state: u16,
    /// Device-specific state.
    pub device_state: u16,
}

impl Default for AdsDeviceState {
    fn default() -> Self {
        Self {
            ads_state: ADSSTATE_RUN,
            device_state: 0,
        }
    }
}

/// One ADS notification sample carried by a `DeviceNotification` push.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NotificationSample {
    /// ADS notification handle returned by `AddDeviceNotification`.
    pub handle: u32,
    /// Raw ADS value bytes for this sample.
    pub data: Vec<u8>,
}

impl NotificationSample {
    /// Creates a notification sample.
    #[must_use]
    pub fn new(handle: u32, data: impl Into<Vec<u8>>) -> Self {
        Self {
            handle,
            data: data.into(),
        }
    }

    /// Creates an invalidated-handle notification with zero data bytes.
    #[must_use]
    pub fn invalidated(handle: u32) -> Self {
        Self {
            handle,
            data: Vec::new(),
        }
    }
}

/// One ADS notification stamp grouping samples under one FILETIME timestamp.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NotificationStamp {
    /// Windows FILETIME timestamp: 100 ns ticks since 1601-01-01 UTC.
    pub timestamp_filetime: u64,
    /// Samples delivered for this timestamp.
    pub samples: Vec<NotificationSample>,
}

impl NotificationStamp {
    /// Creates a notification stamp.
    #[must_use]
    pub fn new(timestamp_filetime: u64, samples: Vec<NotificationSample>) -> Self {
        Self {
            timestamp_filetime,
            samples,
        }
    }
}

/// Client endpoint that receives an active ADS notification registration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct NotificationReceiver {
    /// Target AMS Net ID for unsolicited `DeviceNotification` frames.
    pub net_id: AmsNetIdBytes,
    /// Target ADS port for unsolicited `DeviceNotification` frames.
    pub port: u16,
}

/// Trait-backed command execution context.
pub struct CommandContext<'a> {
    /// Current ADS client identity.
    pub client: &'a ClientId,
    /// Symbol table provider.
    pub symbols: &'a dyn SymbolSource,
    /// Value reader.
    pub values: &'a dyn ValueIo,
    /// Runtime write port.
    pub writes: &'a dyn RuntimeWritePort,
    /// Client allowlist policy.
    pub policy: &'a dyn ClientPolicy,
    /// Audit sink.
    pub audit: &'a dyn AuditSink,
    /// Clock.
    pub clock: &'a dyn Clock,
    /// Device info response fields.
    pub device_info: DeviceInfo,
    /// ADS state response fields.
    pub device_state: AdsDeviceState,
    /// Logical ADS runtime port served by this command context.
    pub ads_port: u16,
    /// Receiver endpoint for notification registrations created by this command.
    pub notification_receiver: Option<NotificationReceiver>,
}

impl<'a> CommandContext<'a> {
    /// Creates a command context with default device metadata.
    #[must_use]
    pub fn new(
        client: &'a ClientId,
        symbols: &'a dyn SymbolSource,
        values: &'a dyn ValueIo,
        writes: &'a dyn RuntimeWritePort,
        policy: &'a dyn ClientPolicy,
        audit: &'a dyn AuditSink,
        clock: &'a dyn Clock,
    ) -> Self {
        Self {
            client,
            symbols,
            values,
            writes,
            policy,
            audit,
            clock,
            device_info: DeviceInfo::default(),
            device_state: AdsDeviceState::default(),
            ads_port: 851,
            notification_receiver: None,
        }
    }

    /// Returns this context with an ADS notification receiver endpoint.
    #[must_use]
    pub fn with_notification_receiver(mut self, receiver: NotificationReceiver) -> Self {
        self.notification_receiver = Some(receiver);
        self
    }
}

mod requests;
mod wire;

pub use wire::build_device_notification_payload;

use self::requests::{AddNotificationRequest, IndexLengthRequest, ReadWriteRequest, WriteRequest};
use self::wire::{
    add_notification_response, error_response, push_result, read_response, read_u32,
    serialize_datatype_table, serialize_symbol_entry, serialize_symbol_table, sized_data,
    sized_value_data, u32_len, unique_datatype_descriptors, write_result,
};

/// Stateful ADS command dispatcher.
#[derive(Debug, Default)]
pub struct CommandDispatcher {
    next_handle: u32,
    handles: BTreeMap<u32, SymbolDescriptor>,
    next_notification_handle: u32,
    notifications: BTreeMap<u32, ActiveNotification>,
    max_notifications: usize,
    max_sumup_items: usize,
    max_write_bytes: usize,
    max_handles: usize,
}

/// Active ADS device-notification registration owned by one client connection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ActiveNotification {
    /// Client endpoint that registered this notification handle.
    pub receiver: NotificationReceiver,
    /// ADS notification handle returned to the client.
    pub handle: u32,
    /// Resolved source watched by this notification.
    pub target: NotificationTarget,
    /// Requested byte length.
    pub byte_len: u32,
    /// ADS transmission mode.
    pub transmission_mode: u32,
    /// Requested maximum delay in milliseconds.
    pub max_delay_ms: u32,
    /// Requested cycle time in milliseconds.
    pub cycle_time_ms: u32,
}

/// Source watched by one ADS device-notification registration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NotificationTarget {
    /// A runtime symbol value.
    Symbol(SymbolDescriptor),
    /// Static hidden system-symbol bytes.
    SystemBytes(Vec<u8>),
    /// The ADS symbol-version counter exposed by `ADSIGRP_SYM_VERSION`.
    SymbolVersion,
}

impl CommandDispatcher {
    /// Creates an empty dispatcher.
    #[must_use]
    pub fn new() -> Self {
        Self {
            next_handle: 1,
            handles: BTreeMap::new(),
            next_notification_handle: 1,
            notifications: BTreeMap::new(),
            max_notifications: usize::MAX,
            max_sumup_items: usize::MAX,
            max_write_bytes: usize::MAX,
            max_handles: DEFAULT_MAX_HANDLES_PER_CLIENT,
        }
    }

    /// Creates a dispatcher with a per-connection notification limit.
    #[must_use]
    pub fn with_max_notifications(max_notifications: usize) -> Self {
        Self {
            max_notifications,
            ..Self::new()
        }
    }

    /// Creates a dispatcher with explicit per-client resource limits.
    #[must_use]
    pub fn with_limits(
        max_notifications: usize,
        max_sumup_items: usize,
        max_write_bytes: usize,
        max_handles: usize,
    ) -> Self {
        Self {
            max_notifications,
            max_sumup_items,
            max_write_bytes,
            max_handles,
            ..Self::new()
        }
    }

    /// Dispatches one ADS command payload and returns the ADS command response payload.
    #[must_use]
    pub fn dispatch(
        &mut self,
        command_id: CommandId,
        payload: &[u8],
        ctx: &CommandContext<'_>,
    ) -> Vec<u8> {
        if !ctx.policy.permits(ctx.client) {
            ctx.audit.record(&AdsServerAuditEvent::new(
                AdsServerAuditKind::PolicyRejected,
                ctx.client.clone(),
                None,
                Err(AdsServerError::device(
                    AdsErrorCode::AccessDenied,
                    "ADS client is not allowed",
                )),
                ctx.clock.now_ms(),
            ));
            return error_response(command_id, AdsErrorCode::AccessDenied);
        }

        match command_id {
            CommandId::ReadDeviceInfo => Self::read_device_info(payload, ctx),
            CommandId::Read => self.read(payload, ctx),
            CommandId::Write => self.write(payload, ctx),
            CommandId::ReadState => Self::read_state(payload, ctx),
            CommandId::WriteControl => Self::write_control(payload),
            CommandId::AddDeviceNotification => self.add_device_notification(payload, ctx),
            CommandId::DeleteDeviceNotification => self.delete_device_notification(payload),
            CommandId::DeviceNotification => write_result(AdsErrorCode::ServiceNotSupported),
            CommandId::ReadWrite => self.read_write(payload, ctx),
        }
    }

    /// Returns the number of live symbol handles.
    #[must_use]
    pub fn handle_count(&self) -> usize {
        self.handles.len()
    }

    #[cfg(test)]
    fn set_next_handle_for_test(&mut self, next_handle: u32) {
        self.next_handle = next_handle.max(1);
    }

    /// Returns the number of live notification registrations.
    #[must_use]
    pub fn notification_count(&self) -> usize {
        self.notifications.len()
    }

    /// Returns current notification registrations.
    #[must_use]
    pub fn active_notifications(&self) -> Vec<ActiveNotification> {
        self.notifications.values().cloned().collect()
    }

    fn read_device_info(payload: &[u8], ctx: &CommandContext<'_>) -> Vec<u8> {
        if !payload.is_empty() {
            return write_result(AdsErrorCode::InvalidSize);
        }

        let mut response = Vec::with_capacity(24);
        push_result(&mut response, AdsErrorCode::NoError);
        response.push(ctx.device_info.major_version);
        response.push(ctx.device_info.minor_version);
        response.extend_from_slice(&ctx.device_info.build.to_le_bytes());
        let mut name = [0_u8; 16];
        let bytes = ctx.device_info.name.as_bytes();
        let len = bytes.len().min(name.len());
        name[..len].copy_from_slice(&bytes[..len]);
        response.extend_from_slice(&name);
        response
    }

    fn read(&self, payload: &[u8], ctx: &CommandContext<'_>) -> Vec<u8> {
        let request = match IndexLengthRequest::parse(payload) {
            Ok(request) => request,
            Err(code) => return read_response(code, &[]),
        };
        let (code, data) = self.read_address(
            request.index_group,
            request.index_offset,
            request.length,
            ctx,
        );
        read_response(code, &data)
    }

    fn write(&mut self, payload: &[u8], ctx: &CommandContext<'_>) -> Vec<u8> {
        let request = match WriteRequest::parse(payload) {
            Ok(request) => request,
            Err(code) => return write_result(code),
        };
        let code = self.write_address(request.index_group, request.index_offset, request.data, ctx);
        write_result(code)
    }

    fn read_state(payload: &[u8], ctx: &CommandContext<'_>) -> Vec<u8> {
        if !payload.is_empty() {
            return write_result(AdsErrorCode::InvalidSize);
        }
        let mut response = Vec::with_capacity(8);
        push_result(&mut response, AdsErrorCode::NoError);
        response.extend_from_slice(&ctx.device_state.ads_state.to_le_bytes());
        response.extend_from_slice(&ctx.device_state.device_state.to_le_bytes());
        response
    }

    fn write_control(payload: &[u8]) -> Vec<u8> {
        if payload.len() < 8 {
            return write_result(AdsErrorCode::InvalidSize);
        }
        let data_len = match read_u32(payload, 4) {
            Ok(data_len) => data_len as usize,
            Err(code) => return write_result(code),
        };
        if payload.len() != 8 + data_len {
            return write_result(AdsErrorCode::InvalidSize);
        }
        write_result(AdsErrorCode::ServiceNotSupported)
    }

    fn add_device_notification(&mut self, payload: &[u8], ctx: &CommandContext<'_>) -> Vec<u8> {
        let Some(receiver) = ctx.notification_receiver else {
            return add_notification_response(AdsErrorCode::ServiceNotSupported, 0);
        };
        let request = match AddNotificationRequest::parse(payload) {
            Ok(request) => request,
            Err(code) => return add_notification_response(code, 0),
        };
        if !matches!(
            request.transmission_mode,
            ADSTRANS_SERVERCYCLE | ADSTRANS_SERVERONCHA
        ) {
            return add_notification_response(AdsErrorCode::TransmissionModeNotSupported, 0);
        }
        if self.notifications.len() >= self.max_notifications {
            return add_notification_response(AdsErrorCode::NoMemory, 0);
        }
        let (target, max_byte_len) = if request.index_group == ADSIGRP_SYM_VERSION {
            if request.index_offset != 0 {
                return add_notification_response(AdsErrorCode::InvalidOffset, 0);
            }
            (NotificationTarget::SymbolVersion, 4)
        } else if request.index_group == ADSIGRP_SYM_VALBYHND {
            match self.handles.get(&request.index_offset).cloned() {
                Some(symbol) => notification_target_for_symbol(&symbol, ctx),
                None => return add_notification_response(AdsErrorCode::InvalidOffset, 0),
            }
        } else {
            match Self::resolve_symbol(request.index_group, request.index_offset, ctx) {
                Some(symbol) => notification_target_for_symbol(&symbol, ctx),
                None => return add_notification_response(AdsErrorCode::InvalidOffset, 0),
            }
        };
        if request.byte_len == 0 || request.byte_len > max_byte_len {
            return add_notification_response(AdsErrorCode::InvalidWatchSize, 0);
        }

        let handle = self.next_notification_handle;
        self.next_notification_handle = self.next_notification_handle.saturating_add(1).max(1);
        self.notifications.insert(
            handle,
            ActiveNotification {
                receiver,
                handle,
                target,
                byte_len: request.byte_len,
                transmission_mode: request.transmission_mode,
                max_delay_ms: request.max_delay_ms,
                cycle_time_ms: request.cycle_time_ms,
            },
        );
        add_notification_response(AdsErrorCode::NoError, handle)
    }

    fn delete_device_notification(&mut self, payload: &[u8]) -> Vec<u8> {
        if payload.len() != 4 {
            return write_result(AdsErrorCode::InvalidSize);
        }
        let handle = match read_u32(payload, 0) {
            Ok(handle) => handle,
            Err(code) => return write_result(code),
        };
        if self.notifications.remove(&handle).is_some() {
            write_result(AdsErrorCode::NoError)
        } else {
            write_result(AdsErrorCode::NotificationHandleInvalid)
        }
    }

    fn read_write(&mut self, payload: &[u8], ctx: &CommandContext<'_>) -> Vec<u8> {
        let request = match ReadWriteRequest::parse(payload) {
            Ok(request) => request,
            Err(code) => return read_response(code, &[]),
        };

        match request.index_group {
            ADSIGRP_SYM_HNDBYNAME => {
                let (code, data) =
                    self.handle_by_name(request.write_data, request.read_length, ctx);
                read_response(code, &data)
            }
            ADSIGRP_SYM_RELEASEHND => {
                let code = self.release_handle(request.index_offset, request.write_data);
                read_response(code, &[])
            }
            ADSIGRP_SYM_VALBYNAME => {
                let (code, data) =
                    Self::symbol_value_by_name(request.write_data, request.read_length, ctx);
                read_response(code, &data)
            }
            ADSIGRP_SYM_INFOBYNAME => {
                let (code, data) =
                    Self::symbol_info_by_name(request.write_data, request.read_length, ctx);
                read_response(code, &data)
            }
            ADSIGRP_SYM_INFOBYNAMEEX => {
                let (code, data) =
                    Self::symbol_info_by_name_ex(request.write_data, request.read_length, ctx);
                read_response(code, &data)
            }
            ADSIGRP_SUMUP_READ => self.sumup_read(request, ctx),
            ADSIGRP_SUMUP_READ_EX => self.sumup_read_ex(request, ctx),
            ADSIGRP_SUMUP_WRITE => self.sumup_write(request, ctx),
            ADSIGRP_SUMUP_READWRITE => self.sumup_read_write(request, ctx),
            _ => {
                let (code, data) = self.read_address(
                    request.index_group,
                    request.index_offset,
                    request.read_length,
                    ctx,
                );
                read_response(code, &data)
            }
        }
    }

    fn handle_by_name(
        &mut self,
        write_data: &[u8],
        read_length: u32,
        ctx: &CommandContext<'_>,
    ) -> (AdsErrorCode, Vec<u8>) {
        if read_length < 4 {
            return (AdsErrorCode::InvalidSize, Vec::new());
        }
        let Some(name) = ads_name_string(write_data) else {
            return (AdsErrorCode::InvalidData, Vec::new());
        };
        let Some(symbol) = Self::resolve_symbol_by_name(name, ctx) else {
            return (AdsErrorCode::SymbolNotFound, Vec::new());
        };
        if self.handles.len() >= self.max_handles {
            return (AdsErrorCode::NoMemory, Vec::new());
        }
        let Some(handle) = self.allocate_handle(symbol) else {
            return (AdsErrorCode::NoMemory, Vec::new());
        };
        (AdsErrorCode::NoError, handle.to_le_bytes().to_vec())
    }

    fn allocate_handle(&mut self, symbol: SymbolDescriptor) -> Option<u32> {
        let search_budget = self.handles.len().saturating_add(1).max(1);
        for _ in 0..search_budget {
            let handle = self.next_handle.max(1);
            self.next_handle = self.next_handle.wrapping_add(1).max(1);
            if self.handles.contains_key(&handle) {
                continue;
            }
            self.handles.insert(handle, symbol);
            return Some(handle);
        }
        None
    }

    fn release_handle(&mut self, index_offset: u32, write_data: &[u8]) -> AdsErrorCode {
        let handle = if write_data.is_empty() {
            index_offset
        } else {
            if write_data.len() != 4 {
                return AdsErrorCode::InvalidSize;
            }
            let Ok(handle) = read_u32(write_data, 0) else {
                return AdsErrorCode::InvalidSize;
            };
            handle
        };
        if self.handles.remove(&handle).is_some() {
            AdsErrorCode::NoError
        } else {
            AdsErrorCode::InvalidOffset
        }
    }

    fn symbol_value_by_name(
        write_data: &[u8],
        read_length: u32,
        ctx: &CommandContext<'_>,
    ) -> (AdsErrorCode, Vec<u8>) {
        let Some(name) = ads_name_string(write_data) else {
            return (AdsErrorCode::InvalidData, Vec::new());
        };
        let symbol = Self::resolve_symbol_by_name(name, ctx);
        let Some(symbol) = symbol else {
            return (AdsErrorCode::SymbolNotFound, Vec::new());
        };
        Self::read_symbol(&symbol, read_length, ctx)
    }

    fn symbol_info_by_name(
        write_data: &[u8],
        read_length: u32,
        ctx: &CommandContext<'_>,
    ) -> (AdsErrorCode, Vec<u8>) {
        let Some(name) = ads_name_string(write_data) else {
            return (AdsErrorCode::InvalidData, Vec::new());
        };
        let symbol = Self::resolve_symbol_by_name(name, ctx);
        let Some(symbol) = symbol else {
            return (AdsErrorCode::SymbolNotFound, Vec::new());
        };
        let mut data = Vec::with_capacity(12);
        data.extend_from_slice(&symbol.index_group.to_le_bytes());
        data.extend_from_slice(&symbol.index_offset.to_le_bytes());
        data.extend_from_slice(&symbol.byte_size.to_le_bytes());
        sized_value_data(data, read_length)
    }

    fn symbol_info_by_name_ex(
        write_data: &[u8],
        read_length: u32,
        ctx: &CommandContext<'_>,
    ) -> (AdsErrorCode, Vec<u8>) {
        let Some(name) = ads_name_string(write_data) else {
            return (AdsErrorCode::InvalidData, Vec::new());
        };
        let symbol = Self::resolve_symbol_by_name(name, ctx);
        let Some(symbol) = symbol else {
            return (AdsErrorCode::SymbolNotFound, Vec::new());
        };
        match serialize_symbol_entry(&symbol) {
            Ok(entry) => sized_data(entry, read_length),
            Err(code) => (code, Vec::new()),
        }
    }

    fn read_address(
        &self,
        index_group: u32,
        index_offset: u32,
        read_length: u32,
        ctx: &CommandContext<'_>,
    ) -> (AdsErrorCode, Vec<u8>) {
        if let Some(data) = system_symbols::device_data(index_group, index_offset) {
            return sized_data(data, read_length);
        }
        match index_group {
            ADSIGRP_SYM_VERSION => {
                return sized_data(ctx.symbols.version().to_le_bytes().to_vec(), read_length)
            }
            ADSIGRP_SYM_UPLOADINFO => return Self::symbol_upload_info(read_length, ctx),
            ADSIGRP_SYM_UPLOADINFO2 => return Self::symbol_upload_info2(read_length, ctx),
            ADSIGRP_SYM_UPLOAD => {
                let snapshot = ctx.symbols.snapshot();
                return match serialize_symbol_table(snapshot.symbols.as_slice()) {
                    Ok(table) => sized_data(table, read_length),
                    Err(code) => (code, Vec::new()),
                };
            }
            ADSIGRP_SYM_DT_UPLOAD => {
                let snapshot = ctx.symbols.snapshot();
                return match serialize_datatype_table(snapshot.symbols.as_slice()) {
                    Ok(table) => sized_data(table, read_length),
                    Err(code) => (code, Vec::new()),
                };
            }
            ADSIGRP_SYM_VALBYHND => {
                let Some(symbol) = self.handles.get(&index_offset) else {
                    return (AdsErrorCode::InvalidOffset, Vec::new());
                };
                return Self::read_symbol(symbol, read_length, ctx);
            }
            _ => {}
        }

        let Some(symbol) = Self::resolve_symbol(index_group, index_offset, ctx) else {
            return unknown_address_code(index_group, ctx);
        };
        Self::read_symbol(&symbol, read_length, ctx)
    }

    fn read_symbol(
        symbol: &SymbolDescriptor,
        read_length: u32,
        ctx: &CommandContext<'_>,
    ) -> (AdsErrorCode, Vec<u8>) {
        if let Some(bytes) =
            system_symbols::read_symbol(symbol, ctx.symbols.version(), ctx.ads_port)
        {
            return sized_value_data(bytes, read_length);
        }
        match ctx.values.read(symbol) {
            Ok((bytes, _quality)) => sized_value_data(bytes, read_length),
            Err(error) => (error_to_ads_code(&error), Vec::new()),
        }
    }

    fn write_address(
        &mut self,
        index_group: u32,
        index_offset: u32,
        data: &[u8],
        ctx: &CommandContext<'_>,
    ) -> AdsErrorCode {
        if data.len() > self.max_write_bytes {
            return AdsErrorCode::InvalidSize;
        }
        if index_group == ADSIGRP_SYM_RELEASEHND {
            return self.release_handle(index_offset, data);
        }

        let symbol = if index_group == ADSIGRP_SYM_VALBYHND {
            self.handles.get(&index_offset).cloned()
        } else {
            Self::resolve_symbol(index_group, index_offset, ctx)
        };
        let Some(symbol) = symbol else {
            return unknown_address_code(index_group, ctx).0;
        };

        Self::write_symbol(&symbol, data, ctx)
    }

    fn write_symbol(
        symbol: &SymbolDescriptor,
        data: &[u8],
        ctx: &CommandContext<'_>,
    ) -> AdsErrorCode {
        if !symbol.flags.contains(&SymbolFlag::Write) {
            let error =
                AdsServerError::device(AdsErrorCode::InvalidAccess, "ADS symbol is not writable");
            Self::audit_write(ctx, AdsServerAuditKind::WriteRejected, symbol, Err(error));
            return AdsErrorCode::InvalidAccess;
        }

        match ctx.writes.write(symbol, data, ctx.client) {
            Ok(()) => {
                Self::audit_write(ctx, AdsServerAuditKind::WriteAccepted, symbol, Ok(()));
                AdsErrorCode::NoError
            }
            Err(error) => {
                let code = error_to_ads_code(&error);
                Self::audit_write(ctx, AdsServerAuditKind::WriteRejected, symbol, Err(error));
                code
            }
        }
    }

    fn audit_write(
        ctx: &CommandContext<'_>,
        kind: AdsServerAuditKind,
        symbol: &SymbolDescriptor,
        result: Result<(), AdsServerError>,
    ) {
        ctx.audit.record(
            &AdsServerAuditEvent::new(
                kind,
                ctx.client.clone(),
                Some(symbol.name.clone()),
                result,
                ctx.clock.now_ms(),
            )
            .with_value_type(symbol.data_type.source_name.clone()),
        );
    }

    fn resolve_symbol(
        index_group: u32,
        index_offset: u32,
        ctx: &CommandContext<'_>,
    ) -> Option<SymbolDescriptor> {
        let snapshot = ctx.symbols.snapshot();
        find_symbol_by_address(snapshot.symbols.as_slice(), index_group, index_offset)
            .cloned()
            .or_else(|| system_symbols::symbol_by_address(index_group, index_offset))
    }

    fn resolve_symbol_by_name(name: &str, ctx: &CommandContext<'_>) -> Option<SymbolDescriptor> {
        let snapshot = ctx.symbols.snapshot();
        find_symbol_by_name(snapshot.symbols.as_slice(), name)
            .cloned()
            .or_else(|| system_symbols::symbol_by_name(name))
    }

    fn symbol_upload_info(read_length: u32, ctx: &CommandContext<'_>) -> (AdsErrorCode, Vec<u8>) {
        let snapshot = ctx.symbols.snapshot();
        let symbol_table = match serialize_symbol_table(snapshot.symbols.as_slice()) {
            Ok(table) => table,
            Err(code) => return (code, Vec::new()),
        };
        let symbol_count = match u32_len(snapshot.symbols.len()) {
            Ok(count) => count,
            Err(code) => return (code, Vec::new()),
        };
        let symbol_table_len = match u32_len(symbol_table.len()) {
            Ok(len) => len,
            Err(code) => return (code, Vec::new()),
        };
        let mut data = Vec::with_capacity(8);
        data.extend_from_slice(&symbol_count.to_le_bytes());
        data.extend_from_slice(&symbol_table_len.to_le_bytes());
        sized_value_data(data, read_length)
    }

    fn symbol_upload_info2(read_length: u32, ctx: &CommandContext<'_>) -> (AdsErrorCode, Vec<u8>) {
        let snapshot = ctx.symbols.snapshot();
        let symbol_table = match serialize_symbol_table(snapshot.symbols.as_slice()) {
            Ok(table) => table,
            Err(code) => return (code, Vec::new()),
        };
        let datatype_table = match serialize_datatype_table(snapshot.symbols.as_slice()) {
            Ok(table) => table,
            Err(code) => return (code, Vec::new()),
        };
        let datatype_count = unique_datatype_descriptors(snapshot.symbols.as_slice()).len();
        let symbol_count = match u32_len(snapshot.symbols.len()) {
            Ok(count) => count,
            Err(code) => return (code, Vec::new()),
        };
        let symbol_table_len = match u32_len(symbol_table.len()) {
            Ok(len) => len,
            Err(code) => return (code, Vec::new()),
        };
        let datatype_count = match u32_len(datatype_count) {
            Ok(count) => count,
            Err(code) => return (code, Vec::new()),
        };
        let datatype_table_len = match u32_len(datatype_table.len()) {
            Ok(len) => len,
            Err(code) => return (code, Vec::new()),
        };
        let mut data = Vec::with_capacity(24);
        data.extend_from_slice(&symbol_count.to_le_bytes());
        data.extend_from_slice(&symbol_table_len.to_le_bytes());
        data.extend_from_slice(&datatype_count.to_le_bytes());
        data.extend_from_slice(&datatype_table_len.to_le_bytes());
        data.extend_from_slice(&0_u32.to_le_bytes());
        data.extend_from_slice(&0_u32.to_le_bytes());
        sized_value_data(data, read_length)
    }

    fn sumup_read(&self, request: ReadWriteRequest<'_>, ctx: &CommandContext<'_>) -> Vec<u8> {
        let count = request.index_offset as usize;
        if count == 0 {
            return read_response(AdsErrorCode::ServiceNotSupported, &[]);
        }
        if count > self.max_sumup_items {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        let Some(header_len) = count.checked_mul(12) else {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        };
        if request.write_data.len() != header_len {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }

        let mut metadata = Vec::with_capacity(count * 4);
        let mut data = Vec::new();
        for index in 0..count {
            let offset = index * 12;
            let index_group = read_u32(request.write_data, offset).unwrap_or(0);
            let index_offset = read_u32(request.write_data, offset + 4).unwrap_or(0);
            let read_length = read_u32(request.write_data, offset + 8).unwrap_or(0);
            let (code, item_data) = self.read_address(index_group, index_offset, read_length, ctx);
            push_result(&mut metadata, code);
            if code == AdsErrorCode::NoError {
                data.extend(item_data);
            }
        }
        metadata.extend(data);
        read_response(AdsErrorCode::NoError, &metadata)
    }

    fn sumup_read_ex(&self, request: ReadWriteRequest<'_>, ctx: &CommandContext<'_>) -> Vec<u8> {
        let count = request.index_offset as usize;
        if count == 0 {
            return read_response(AdsErrorCode::ServiceNotSupported, &[]);
        }
        if count > self.max_sumup_items {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        let Some(header_len) = count.checked_mul(12) else {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        };
        if request.write_data.len() != header_len {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }

        let mut metadata = Vec::with_capacity(count * 8);
        let mut data = Vec::new();
        for index in 0..count {
            let offset = index * 12;
            let index_group = read_u32(request.write_data, offset).unwrap_or(0);
            let index_offset = read_u32(request.write_data, offset + 4).unwrap_or(0);
            let read_length = read_u32(request.write_data, offset + 8).unwrap_or(0);
            let (code, item_data) = self.read_address(index_group, index_offset, read_length, ctx);
            push_result(&mut metadata, code);
            if code == AdsErrorCode::NoError {
                let Ok(item_len) = u32_len(item_data.len()) else {
                    metadata.extend_from_slice(&0_u32.to_le_bytes());
                    continue;
                };
                metadata.extend_from_slice(&item_len.to_le_bytes());
                data.extend(item_data);
            } else {
                metadata.extend_from_slice(&0_u32.to_le_bytes());
            }
        }
        metadata.extend(data);
        read_response(AdsErrorCode::NoError, &metadata)
    }

    fn sumup_write(&mut self, request: ReadWriteRequest<'_>, ctx: &CommandContext<'_>) -> Vec<u8> {
        let count = request.index_offset as usize;
        if count > self.max_sumup_items {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        let Some(header_len) = count.checked_mul(12) else {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        };
        if request.write_data.len() < header_len {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        if request.write_data.len().saturating_sub(header_len) > self.max_write_bytes {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }

        let mut write_offset = header_len;
        let mut response_data = Vec::with_capacity(count * 4);
        for index in 0..count {
            let offset = index * 12;
            let index_group = read_u32(request.write_data, offset).unwrap_or(0);
            let index_offset = read_u32(request.write_data, offset + 4).unwrap_or(0);
            let write_length = read_u32(request.write_data, offset + 8).unwrap_or(0) as usize;
            let Some(end) = write_offset.checked_add(write_length) else {
                push_result(&mut response_data, AdsErrorCode::InvalidSize);
                continue;
            };
            let Some(data) = request.write_data.get(write_offset..end) else {
                push_result(&mut response_data, AdsErrorCode::InvalidSize);
                write_offset = end;
                continue;
            };
            write_offset = end;
            let code = self.write_address(index_group, index_offset, data, ctx);
            push_result(&mut response_data, code);
        }
        if write_offset != request.write_data.len() {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        read_response(AdsErrorCode::NoError, &response_data)
    }

    fn sumup_read_write(
        &mut self,
        request: ReadWriteRequest<'_>,
        ctx: &CommandContext<'_>,
    ) -> Vec<u8> {
        let count = request.index_offset as usize;
        if count > self.max_sumup_items {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        let Some(header_len) = count.checked_mul(16) else {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        };
        if request.write_data.len() < header_len {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        if request.write_data.len().saturating_sub(header_len) > self.max_write_bytes {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }

        let mut write_offset = header_len;
        let mut metadata = Vec::with_capacity(count * 8);
        let mut read_data = Vec::new();
        for index in 0..count {
            let offset = index * 16;
            let index_group = read_u32(request.write_data, offset).unwrap_or(0);
            let index_offset = read_u32(request.write_data, offset + 4).unwrap_or(0);
            let read_length = read_u32(request.write_data, offset + 8).unwrap_or(0);
            let write_length = read_u32(request.write_data, offset + 12).unwrap_or(0) as usize;
            let Some(end) = write_offset.checked_add(write_length) else {
                push_result(&mut metadata, AdsErrorCode::InvalidSize);
                metadata.extend_from_slice(&0_u32.to_le_bytes());
                continue;
            };
            let Some(data) = request.write_data.get(write_offset..end) else {
                push_result(&mut metadata, AdsErrorCode::InvalidSize);
                metadata.extend_from_slice(&0_u32.to_le_bytes());
                write_offset = end;
                continue;
            };
            write_offset = end;

            let write_code = if write_length == 0 {
                AdsErrorCode::NoError
            } else {
                self.write_address(index_group, index_offset, data, ctx)
            };
            if write_code != AdsErrorCode::NoError {
                push_result(&mut metadata, write_code);
                metadata.extend_from_slice(&0_u32.to_le_bytes());
                continue;
            }
            let (read_code, item_data) =
                self.read_address(index_group, index_offset, read_length, ctx);
            push_result(&mut metadata, read_code);
            if read_code == AdsErrorCode::NoError {
                let Ok(item_len) = u32_len(item_data.len()) else {
                    push_result(&mut metadata, AdsErrorCode::InvalidSize);
                    metadata.extend_from_slice(&0_u32.to_le_bytes());
                    continue;
                };
                metadata.extend_from_slice(&item_len.to_le_bytes());
                read_data.extend(item_data);
            } else {
                metadata.extend_from_slice(&0_u32.to_le_bytes());
            }
        }
        if write_offset != request.write_data.len() {
            return read_response(AdsErrorCode::InvalidSize, &[]);
        }
        metadata.extend(read_data);
        read_response(AdsErrorCode::NoError, &metadata)
    }
}

fn unknown_address_code(index_group: u32, ctx: &CommandContext<'_>) -> (AdsErrorCode, Vec<u8>) {
    if ctx
        .symbols
        .snapshot()
        .symbols
        .iter()
        .any(|symbol| symbol.index_group == index_group)
    {
        (AdsErrorCode::InvalidOffset, Vec::new())
    } else {
        (AdsErrorCode::InvalidGroup, Vec::new())
    }
}

fn error_to_ads_code(error: &AdsServerError) -> AdsErrorCode {
    error.code()
}

fn notification_target_for_symbol(
    symbol: &SymbolDescriptor,
    ctx: &CommandContext<'_>,
) -> (NotificationTarget, u32) {
    if system_symbols::is_online_change_count_symbol(symbol) {
        (NotificationTarget::SymbolVersion, symbol.byte_size)
    } else if let Some(bytes) =
        system_symbols::read_symbol(symbol, ctx.symbols.version(), ctx.ads_port)
    {
        (NotificationTarget::SystemBytes(bytes), symbol.byte_size)
    } else {
        (NotificationTarget::Symbol(symbol.clone()), symbol.byte_size)
    }
}

fn find_symbol_by_address(
    symbols: &[SymbolDescriptor],
    index_group: u32,
    index_offset: u32,
) -> Option<&SymbolDescriptor> {
    symbols
        .iter()
        .find(|symbol| symbol.index_group == index_group && symbol.index_offset == index_offset)
}

fn find_symbol_by_name<'a>(
    symbols: &'a [SymbolDescriptor],
    name: &str,
) -> Option<&'a SymbolDescriptor> {
    symbols.iter().find(|symbol| symbol.name == name)
}

fn ads_name_string(bytes: &[u8]) -> Option<&str> {
    match bytes.iter().position(|byte| *byte == 0) {
        Some(end) => std::str::from_utf8(bytes.get(..end)?).ok(),
        None => std::str::from_utf8(bytes).ok(),
    }
}

#[cfg(test)]
mod tests;
