include!("tests/helpers.rs");
include!("tests/ads_product_surfaces.rs");
include!("tests/debug_boundary.rs");
include!("tests/audit_durability.rs");
include!("tests/connectors.rs");
include!("tests/goldens.rs");
include!("tests/hmi.rs");
include!("tests/debug_mutation_lifecycle.rs");
include!("tests/core.rs");
