use std::io::{BufRead, BufReader, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
#[cfg(not(feature = "ads-wire"))]
use std::process::Stdio;
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::mpsc::{self, Receiver};
use std::thread::JoinHandle;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use trust_ads_core::{
    AdsDataTypeDescriptor, IecDataType, SymbolDescriptor, SymbolFlag, SymbolSnapshot,
};

static TEMP_COUNTER: AtomicU64 = AtomicU64::new(1);

#[test]
fn ads_validate_cli_returns_nonzero_for_missing_snapshot_symbol() {
    let root = unique_temp_dir("ads-cli-missing-symbol");
    let config = write_ads_config(&root);
    let snapshot = write_snapshot(&root, "line1", vec![]);
    let generated = write_generated_source(&root, "stale\n");

    let output = run_ads_validate(&config, &snapshot, &generated);

    assert_failure_contains(&output, "missing from snapshot");
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn ads_validate_cli_returns_nonzero_for_type_mismatch() {
    let root = unique_temp_dir("ads-cli-type-mismatch");
    let config = write_ads_config(&root);
    let snapshot = write_snapshot(
        &root,
        "line1",
        vec![SymbolDescriptor::new(
            "MAIN.Temperature",
            AdsDataTypeDescriptor::scalar("LREAL", IecDataType::Lreal),
            0x4020,
            0,
            8,
        )
        .with_flag(SymbolFlag::Read)],
    );
    let generated = write_generated_source(&root, "stale\n");

    let output = run_ads_validate(&config, &snapshot, &generated);

    assert_failure_contains(&output, "type mismatch");
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn ads_validate_cli_returns_nonzero_with_first_diff_for_generated_drift() {
    let root = unique_temp_dir("ads-cli-source-drift");
    let config = write_ads_config(&root);
    let snapshot = write_snapshot(
        &root,
        "line1",
        vec![SymbolDescriptor::new(
            "MAIN.Temperature",
            AdsDataTypeDescriptor::scalar("REAL", IecDataType::Real),
            0x4020,
            0,
            4,
        )
        .with_flag(SymbolFlag::Read)],
    );
    let generated = write_generated_source(
        &root,
        concat!(
            "(* Generated by trust-runtime ads import-symbols. Do not edit by hand. *)\n",
            "TYPE\n",
            "    ADS_QUALITY : (Stale := 0, Good := 1, Error := 2);\n",
            "END_TYPE\n",
            "\n",
            "VAR_GLOBAL\n",
            "    (* ADS connection: line1 *)\n",
            "    (* symbol MAIN.Temperature *)\n",
            "    line1_temp : LREAL;\n",
            "    line1_temp_quality : ADS_QUALITY := Stale;\n",
            "END_VAR\n",
        ),
    );

    let output = run_ads_validate(&config, &snapshot, &generated);

    assert_failure_contains(&output, "first difference at line");
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn ads_import_cli_writes_idempotently_and_requires_force_for_drift() {
    let root = unique_temp_dir("ads-cli-import-output");
    let config = write_ads_config(&root);
    let snapshot = write_snapshot(
        &root,
        "line1",
        vec![SymbolDescriptor::new(
            "MAIN.Temperature",
            AdsDataTypeDescriptor::scalar("REAL", IecDataType::Real),
            0x4020,
            0,
            4,
        )
        .with_flag(SymbolFlag::Read)],
    );
    let generated = root.join("nested/generated/ads_generated.st");

    let run_import = |force: bool| {
        let mut command =
            Command::new(std::env::var_os("CARGO_BIN_EXE_trust-runtime").expect(
                "Cargo must provide trust-runtime binary while executing integration tests",
            ));
        command.args([
            "ads",
            "import",
            "--config",
            config.to_str().expect("config path"),
            "--snapshot",
            snapshot.to_str().expect("snapshot path"),
            "--output",
            generated.to_str().expect("generated path"),
            "--json",
        ]);
        if force {
            command.arg("--force");
        }
        command.output().expect("run trust-runtime ads import")
    };

    let first = run_import(false);
    assert_success(&first);
    assert!(String::from_utf8_lossy(&first.stdout).contains("\"changed\": true"));
    assert!(std::fs::read_to_string(&generated)
        .expect("generated source")
        .contains("line1_temp : REAL;"));

    let unchanged = run_import(false);
    assert_success(&unchanged);
    assert!(String::from_utf8_lossy(&unchanged.stdout).contains("\"changed\": false"));

    std::fs::write(&generated, "manually edited\n").expect("edit generated source");
    assert_failure_contains(&run_import(false), "--force");
    let forced = run_import(true);
    assert_success(&forced);
    assert!(std::fs::read_to_string(&generated)
        .expect("forced generated source")
        .contains("line1_temp : REAL;"));

    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn ads_route_script_cli_emits_static_routes_json() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "route-script",
        "--route-name",
        "trust-runtime-line1",
        "--target",
        "192.168.10.5",
        "--target-net-id",
        "5.23.91.12.1.1",
        "--local-ip",
        "192.168.10.20",
        "--local-net-id",
        "192.168.10.20.1.1",
        "--format",
        "staticroutes",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads route-script");

    assert_success(&output);
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("\"kind\": \"static_routes_xml\""));
    assert!(stdout.contains("<Name>trust-runtime-line1</Name>"));
    assert!(stdout.contains("<Address>192.168.10.20</Address>"));
    assert!(stdout.contains("<NetId>192.168.10.20.1.1</NetId>"));
    assert!(!stdout.contains("secret"));
}

#[test]
fn ads_server_route_script_cli_emits_server_specific_static_routes_json() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "server",
        "route-script",
        "--route-name",
        "trust-runtime-server",
        "--server-ip",
        "192.168.10.20",
        "--server-net-id",
        "192.168.10.20.1.1",
        "--format",
        "staticroutes",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads server route-script");

    assert_success(&output);
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("\"kind\": \"static_routes_xml\""));
    assert!(stdout.contains("<Name>trust-runtime-server</Name>"));
    assert!(stdout.contains("<Address>192.168.10.20</Address>"));
    assert!(stdout.contains("<NetId>192.168.10.20.1.1</NetId>"));
    assert!(!stdout.contains("ADS Error 1861"));
    assert!(!stdout.contains("secret"));
}

#[test]
fn ads_server_route_script_cli_human_output_uses_server_wording() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "server",
        "route-script",
        "--route-name",
        "trust-runtime-server",
        "--server-ip",
        "192.168.10.20",
        "--server-net-id",
        "192.168.10.20.1.1",
        "--format",
        "gui",
    ])
    .output()
    .expect("run trust-runtime ads server route-script");

    assert_success(&output);
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("truST ADS server"));
    assert!(stdout.contains("192.168.10.20.1.1"));
    assert!(!stdout.contains("ADS Error 1861"));
}

#[test]
fn ads_server_doctor_cli_requires_external_proof_pair() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args(["ads", "server", "doctor", "--external-kind", "pyads"])
    .output()
    .expect("run trust-runtime ads server doctor");

    assert_failure_contains(
        &output,
        "requires --external-kind and --external-name together",
    );
}

#[cfg(feature = "ads-wire")]
#[test]
fn ads_doctor_write_probe_requires_the_complete_option_triplet() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "doctor",
        "--target",
        "192.0.2.1",
        "--write-symbol",
        "MAIN.SafeProbe",
    ])
    .output()
    .expect("run trust-runtime ads doctor with incomplete write probe");

    assert_failure_contains(
        &output,
        "requires --write-symbol, --write-type, and --write-value together",
    );
}

#[cfg(feature = "ads-wire")]
#[test]
fn ads_doctor_write_probe_rejects_an_invalid_scalar_before_network_use() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "doctor",
        "--target",
        "192.0.2.1",
        "--write-symbol",
        "MAIN.SafeProbe",
        "--write-type",
        "DINT",
        "--write-value",
        "not-an-integer",
    ])
    .output()
    .expect("run trust-runtime ads doctor with invalid write value");

    assert_failure_contains(&output, "invalid DINT write value");
}

#[test]
fn ads_server_json_rejection_exits_nonzero_and_preserves_error() {
    let (endpoint, request_rx, server) = spawn_control_server(serde_json::json!({
        "id": 1,
        "ok": false,
        "error": "ADS server is disabled",
        "error_code": "ads_server_disabled",
    }));

    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "server",
        "status",
        "--endpoint",
        &endpoint,
        "--token",
        "ads-test-token",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads server status --json");
    let request = request_rx.recv().expect("captured ADS server request");
    server.join().expect("ADS control test server");

    assert!(!output.status.success(), "rejected JSON response must fail");
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("ADS server is disabled"),
        "stderr was:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        request,
        serde_json::json!({
            "id": 1,
            "type": "ads.server.status",
            "auth": "ads-test-token",
            "params": {},
        })
    );
}

#[cfg(not(feature = "ads-wire"))]
#[test]
fn ads_discover_cli_requires_ads_wire_feature_without_faking_results() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "discover",
        "--target",
        "192.168.10.5",
        "--target-net-id",
        "5.23.91.12.1.1",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads discover");

    assert_failure_contains(
        &output,
        "requires trust-runtime built with feature 'ads-wire'",
    );
}

#[cfg(not(feature = "ads-wire"))]
#[test]
fn ads_browse_cli_requires_ads_wire_feature_without_faking_results() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "browse",
        "--config",
        "missing-ads.toml",
        "--connection",
        "line1",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads browse");

    assert_failure_contains(
        &output,
        "ADS browse requires trust-runtime built with feature 'ads-wire'",
    );
}

#[cfg(not(feature = "ads-wire"))]
#[test]
fn ads_doctor_cli_requires_ads_wire_feature_without_faking_results() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "doctor",
        "--target",
        "192.168.10.5",
        "--target-net-id",
        "5.23.91.12.1.1",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads doctor");

    assert_failure_contains(
        &output,
        "requires trust-runtime built with feature 'ads-wire'",
    );
}

#[cfg(not(feature = "ads-wire"))]
#[test]
fn ads_validate_live_cli_requires_ads_wire_feature_without_reading_files() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "validate",
        "--live",
        "--config",
        "missing-ads.toml",
        "--generated",
        "missing-ads-generated.st",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads validate --live");

    assert_failure_contains(
        &output,
        "requires trust-runtime built with feature 'ads-wire'",
    );
}

#[cfg(not(feature = "ads-wire"))]
#[test]
fn ads_import_symbols_cli_requires_ads_wire_feature_without_faking_results() {
    let root = unique_temp_dir("ads-cli-import-symbols-no-wire");
    let ads_toml = root.join("ads.toml");
    let generated = root.join("src/generated/ads_generated.st");
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "import-symbols",
        "--target",
        "192.168.10.5",
        "--target-net-id",
        "5.23.91.12.1.1",
        "--out",
        ads_toml.to_str().expect("ads.toml path"),
        "--gen",
        generated.to_str().expect("generated path"),
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads import-symbols");

    assert_failure_contains(
        &output,
        "requires trust-runtime built with feature 'ads-wire'",
    );
    assert!(!ads_toml.exists());
    assert!(!generated.exists());
    let _ = std::fs::remove_dir_all(root);
}

#[test]
fn ads_route_remove_cli_emits_removal_artifact_json() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "route-remove",
        "--route-name",
        "trust-runtime-line1",
        "--json",
    ])
    .output()
    .expect("run trust-runtime ads route-remove");

    assert_success(&output);
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("\"kind\": \"removal_powershell\""));
    assert!(stdout.contains("trust-runtime-line1"));
    assert!(stdout.contains("Remove"));
}

#[test]
fn ads_add_route_cli_rejects_password_argument() {
    let output = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "add-route",
        "--route-name",
        "trust-runtime-line1",
        "--target",
        "192.168.10.5",
        "--target-net-id",
        "5.23.91.12.1.1",
        "--local-ip",
        "192.168.10.20",
        "--local-net-id",
        "192.168.10.20.1.1",
        "--password",
        "secret-from-argv",
    ])
    .output()
    .expect("run trust-runtime ads add-route");

    assert_failure_contains(&output, "unexpected argument '--password'");
}

#[cfg(not(feature = "ads-wire"))]
#[test]
fn ads_add_route_cli_does_not_echo_stdin_password_when_wire_feature_is_absent() {
    let mut child = Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "add-route",
        "--route-name",
        "trust-runtime-line1",
        "--target",
        "192.168.10.5",
        "--target-net-id",
        "5.23.91.12.1.1",
        "--local-ip",
        "192.168.10.20",
        "--local-net-id",
        "192.168.10.20.1.1",
        "--password-stdin",
        "--json",
    ])
    .stdin(Stdio::piped())
    .stdout(Stdio::piped())
    .stderr(Stdio::piped())
    .spawn()
    .expect("spawn trust-runtime ads add-route");
    child
        .stdin
        .as_mut()
        .expect("stdin")
        .write_all(b"super-secret-password\n")
        .expect("write stdin password");
    let output = child.wait_with_output().expect("wait add-route");

    assert_failure_contains(
        &output,
        "requires trust-runtime built with feature 'ads-wire'",
    );
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(!combined.contains("super-secret-password"));
}

fn spawn_control_server(
    response: serde_json::Value,
) -> (String, Receiver<serde_json::Value>, JoinHandle<()>) {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind ADS control test server");
    let endpoint = format!(
        "tcp://{}",
        listener.local_addr().expect("ADS control server address")
    );
    let (request_tx, request_rx) = mpsc::channel();
    let server = std::thread::spawn(move || {
        let (mut stream, _) = listener.accept().expect("accept ADS control client");
        stream
            .set_read_timeout(Some(Duration::from_secs(5)))
            .expect("set ADS control read timeout");
        stream
            .set_write_timeout(Some(Duration::from_secs(5)))
            .expect("set ADS control write timeout");
        let mut reader = BufReader::new(stream.try_clone().expect("clone ADS control stream"));
        let mut line = String::new();
        reader
            .read_line(&mut line)
            .expect("read ADS control request");
        let request = serde_json::from_str(line.trim_end()).expect("parse ADS control request");
        request_tx.send(request).expect("send captured ADS request");
        writeln!(stream, "{}", serde_json::to_string(&response).unwrap())
            .expect("write ADS control response");
    });
    (endpoint, request_rx, server)
}

fn run_ads_validate(config: &Path, snapshot: &Path, generated: &Path) -> Output {
    Command::new(
        std::env::var_os("CARGO_BIN_EXE_trust-runtime")
            .expect("Cargo must provide trust-runtime binary while executing integration tests"),
    )
    .args([
        "ads",
        "validate",
        "--offline",
        "--config",
        config.to_str().expect("config path"),
        "--snapshot",
        snapshot.to_str().expect("snapshot path"),
        "--generated",
        generated.to_str().expect("generated path"),
    ])
    .output()
    .expect("run trust-runtime ads validate")
}

fn assert_success(output: &Output) {
    assert!(
        output.status.success(),
        "expected success\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn assert_failure_contains(output: &Output, expected: &str) {
    assert!(
        !output.status.success(),
        "expected ads validate failure, got success\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(expected),
        "expected stderr to contain {expected:?}\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        stderr
    );
}

fn write_ads_config(root: &Path) -> PathBuf {
    let path = root.join("ads.toml");
    std::fs::write(
        &path,
        r#"
[[connections]]
name = "line1"
target_net_id = "5.23.91.12.1.1"
host = "192.168.10.5"
transport = "plain"
insecure_transport = true

[[connections.points]]
symbol = "MAIN.Temperature"
var = "line1_temp"
type = "REAL"
"#,
    )
    .expect("write ads.toml");
    path
}

fn write_snapshot(root: &Path, route_name: &str, symbols: Vec<SymbolDescriptor>) -> PathBuf {
    let path = root.join("ads/snapshots/line1.symbols.json");
    std::fs::create_dir_all(path.parent().expect("snapshot parent")).expect("mkdir snapshot");
    let snapshot = SymbolSnapshot::new(route_name, symbols);
    std::fs::write(
        &path,
        snapshot.to_deterministic_json().expect("snapshot json"),
    )
    .expect("write snapshot");
    path
}

fn write_generated_source(root: &Path, source: &str) -> PathBuf {
    let path = root.join("src/generated/ads_generated.st");
    std::fs::create_dir_all(path.parent().expect("generated parent")).expect("mkdir generated");
    std::fs::write(&path, source).expect("write generated source");
    path
}

fn unique_temp_dir(prefix: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time before unix epoch")
        .as_nanos();
    let counter = TEMP_COUNTER.fetch_add(1, Ordering::Relaxed);
    let root = std::env::temp_dir().join(format!(
        "trust-runtime-{prefix}-{}-{nanos}-{counter}",
        std::process::id()
    ));
    std::fs::create_dir_all(&root).expect("create temp dir");
    root
}
